/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzeria.view;

import pizzeria.Size;
import pizzeria.Salsa;
import pizzeria.Pizza;
import pizzeria.Masa;
import javax.swing.*;
import java.util.List;

public class PizzeriaUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PizzeriaUI.class.getName());

   // BOTÓN ESTADO PEDIDO
    private javax.swing.JButton btnEstadoPedido;
    public PizzeriaUI(){
        initComponents();
        setTitle("Pizzería Builder");
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        cbSalsa = new javax.swing.JComboBox<>();
        cbSize = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listToppings = new javax.swing.JList<>();
        chkBordes = new javax.swing.JCheckBox();
        chkSinGluten = new javax.swing.JCheckBox();
        btnCrear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResumen = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();
        cbMasa = new javax.swing.JComboBox<>();
        Estado = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 450));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        cbSalsa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tomate", "Blanca", "BBQ", "Pesto" }));
        cbSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSalsaActionPerformed(evt);
            }
        });

        cbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Mediana ", "Familiar" }));

        listToppings.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listToppings.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pepperoni", "Jamón", "Tocino", "Pollo a la parrilla", "Carne molida", "Chorizo", "Anchoas", "Mozzarella", "Parmesano", "Cheddar", "Queso azul", "Provolone", "Ricotta", "Champiñones", "Pimientos (rojo, verde, amarillo)", "Cebolla morada", "Espinaca", "Tomates cherry", "Alcachofas", "Maíz dulce", "Aceitunas negras o verdes", "Albahaca fresca", "Rúcula", "Piña (sí, la famosa pizza hawaiana)", "Jalapeños", "Salsa BBQ o pesto" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listToppings);

        chkBordes.setText("Bordes Rellenos");

        chkSinGluten.setText("Sin gluten");

        btnCrear.setBackground(new java.awt.Color(102, 204, 255));
        btnCrear.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(204, 0, 0));
        btnCrear.setText("CREAR PIZZA");
        btnCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        txtResumen.setColumns(20);
        txtResumen.setRows(5);
        jScrollPane3.setViewportView(txtResumen);

        lblTitulo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblTitulo1.setText("Tipo de salsa");

        lblTitulo2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblTitulo2.setText("Tamaño");

        lblTitulo3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblTitulo3.setText("Tipo de masa");

        cbMasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delgada", "Tradicional", "Pan" }));
        cbMasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMasaActionPerformed(evt);
            }
        });

        Estado.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Estado.setForeground(new java.awt.Color(204, 0, 0));
        Estado.setText("ESTADO PEDIDO");
        Estado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Estado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("PIZZERIA MAJO");

        jTextField2.setEditable(false);
        jTextField2.setText("DISEÑE A SU GUSTO SU PIZZA");

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("PEDIR PIZZA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(chkBordes))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(lblTitulo2)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(90, 90, 90)
                                                        .addComponent(chkSinGluten))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(134, 134, 134)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(cbSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(lblTitulo1))))))
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTitulo3)
                                            .addComponent(cbMasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCrear)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1)
                                .addGap(43, 43, 43)
                                .addComponent(Estado)
                                .addGap(9, 9, 9)))
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitulo2)
                        .addComponent(lblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBordes)
                            .addComponent(chkSinGluten))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSalsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSalsaActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

         // 1. Mapear el combo de tamaño al enum Size
    Size size;
    switch (cbSize.getSelectedIndex()) {
        case 0 -> size = Size.PERSONAL;
        case 1 -> size = Size.MEDIANA;
        case 2 -> size = Size.FAMILIAR;
        default -> size = Size.PERSONAL; // por si acaso
    }

    // 2. Mapear el combo de masa al enum Masa
    Masa masa;
    switch (cbMasa.getSelectedIndex()) { // OJO: cbMasa, no cbSalsa
        case 0 -> masa = Masa.DELGADA;
        case 1 -> masa = Masa.TRADICIONAL;
        case 2 -> masa = Masa.PAN;
        default -> masa = Masa.TRADICIONAL;
    }

    // 3. Mapear el combo de salsa al enum Salsa
    Salsa salsa;
    switch (cbSalsa.getSelectedIndex()) {
        case 0 -> salsa = Salsa.TOMATE;
        case 1 -> salsa = Salsa.BLANCA;
        case 2 -> salsa = Salsa.BBQ;
        case 3 -> salsa = Salsa.PESTO;
        default -> salsa = Salsa.TOMATE;
    }

    // 4. Construir la pizza con el Builder
    Pizza.Builder builder = new Pizza.Builder()
            .size(size)
            .masa(masa)
            .salsa(salsa);

    if (chkBordes.isSelected()) {
        builder.bordesRellenos(true);
    }
    if (chkSinGluten.isSelected()) {
        builder.sinGluten(true);
    }

    Pizza pizza = builder.build();
    txtResumen.setText(pizza.toString());

        
        

    }//GEN-LAST:event_btnCrearActionPerformed

    private void cbMasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMasaActionPerformed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        String resumen = txtResumen.getText();
    if (resumen == null || resumen.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay pedido creado.");
    } else {
        // Ejemplo: mostrar también información de hilos activos
        Thread[] threads = new Thread[Thread.activeCount()];
        Thread.enumerate(threads);
        StringBuilder sb = new StringBuilder("Resumen de Pedido:\n");
        sb.append(resumen).append("\n\nHilos activos:\n");
        for (Thread t : threads) {
            sb.append(t.getName())
              .append(" [").append(t.getState()).append("]\n");
        }
        JOptionPane.showMessageDialog(this, sb.toString());
    }
    }//GEN-LAST:event_EstadoActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new PizzeriaUI().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Estado;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox<String> cbMasa;
    private javax.swing.JComboBox<String> cbSalsa;
    private javax.swing.JComboBox<String> cbSize;
    private javax.swing.JCheckBox chkBordes;
    private javax.swing.JCheckBox chkSinGluten;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JList<String> listToppings;
    private javax.swing.JTextArea txtResumen;
    // End of variables declaration//GEN-END:variables
}
